language: node_js
node_js:
  - 0.10
before_deploy:
  - "npm run buildpkg"
  - "mkdir build"
  - "mv ../fluxr-* ./build"
deploy:
  api_key:
    secure: NPyCFns/At8eWVTV2tDO/KqOxb+PhRmIFBtqSku6wapg4wxB5B8Rmdh2sUcrAAyjeCspYhN4Jc3CThMDWm95zoMku3qT/8fCKswdij4V4JnUNMW8BqmWalna58h/M/LOJ4eRo31bUkYY77EuASMHOUmAZqH+kSiaOa6sex1TGLA=
  container: fluxr
  file: "build/*"
  provider: cloudfiles
  region: SYD
  skip_cleanup: true
  username: thedodd
  on:
    all_branches: true
    tags: true
    repo: TheDodd/fluxr
